name: Feature request
description: Suggest an enhancement for Alt-Click Status
labels: ["type/feat","status/todo"]
body:
  - type: input
    id: area
    attributes:
      label: Area
      description: actionbars, items, unitframes, config, CI, etc.
      placeholder: items
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What and why?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of what must be true
