name: Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch: {}

permissions:
    contents: write

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # packager needs tags/history

            - name: Package & Upload
              uses: BigWigsMods/packager@v2
              env:
                GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
                CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}