name: release-on-tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing tag to (re)package, e.g. v0.3.0f"
        required: true
        default: "v0.3.0f"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Derive tag & version
        id: meta
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF_NAME}"
          fi
          if [[ -z "$TAG" ]]; then
            echo "::error::No tag provided or detected."
            exit 1
          fi
          VERSION="${TAG#v}"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "TAG=${TAG}" >> "$GITHUB_ENV"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.meta.outputs.tag }}

      - name: Verify tag exists
        shell: bash
        run: |
          if ! git show-ref --tags --verify --quiet "refs/tags/${{ steps.meta.outputs.tag }}"; then
            echo "::error::Tag '${{ steps.meta.outputs.tag }}' does not exist."
            exit 1
          fi

      - name: Preflight: show repo tree (first 200 files)
        run: |
          git ls-tree -r --name-only HEAD | sed -n '1,200p' || true

      - name: Preflight: locate TOC at tag
        id: toc
        shell: bash
        run: |
          set -euo pipefail
          FOUND=""
          if [[ -f "AltClickStatus/AltClickStatus.toc" ]]; then
            FOUND="AltClickStatus/AltClickStatus.toc"
          elif [[ -f "Interface/AddOns/AltClickStatus/AltClickStatus.toc" ]]; then
            FOUND="Interface/AddOns/AltClickStatus/AltClickStatus.toc"
          fi
          echo "found=${FOUND}" >> "$GITHUB_OUTPUT"
          if [[ -z "$FOUND" ]]; then
            echo "::error::Could not find AltClickStatus.toc at tag '${{ steps.meta.outputs.tag }}'."
            echo "Expected one of:"
            echo "  - AltClickStatus/AltClickStatus.toc"
            echo "  - Interface/AddOns/AltClickStatus/AltClickStatus.toc"
            echo "Tip: ensure the tag includes .pkgmeta and the TOC file."
            exit 1
          fi
          echo "Found TOC at $FOUND"

      # ---------------- GitHub Release ZIP (underscore + folder inside) ----------------
      - name: Prepare ZIP package for GitHub Release
        shell: bash
        run: |
          set -euo pipefail
          SRC_DIR="$(dirname "${{ steps.toc.outputs.found }}")"
          ADDON="AltClickStatus"
          mkdir -p pkg/"${ADDON}"
          rsync -a --delete --exclude ".git" --exclude ".github" --exclude "pkg" "${SRC_DIR}/" "pkg/${ADDON}/"

          # For GitHub ZIP we keep explicit version in TOC (packaged copy only)
          if grep -qE '^##\s*Version:' "pkg/${ADDON}/${ADDON}.toc"; then
            sed -i -E "s/^(##\s*Version:)\s*.*/\1 ${{ steps.meta.outputs.version }}/" "pkg/${ADDON}/${ADDON}.toc"
          else
            echo "## Version: ${{ steps.meta.outputs.version }}" >> "pkg/${ADDON}/${ADDON}.toc"
          fi
          cd pkg
          ZIP="${ADDON}_${{ steps.meta.outputs.tag }}.zip"
          zip -r "$ZIP" "${ADDON}"
          echo "ZIP_PATH=${PWD}/${ZIP}" >> $GITHUB_ENV

      - name: Upload artifact (GitHub zip)
        uses: actions/upload-artifact@v4
        with:
          name: AltClickStatus_${{ steps.meta.outputs.tag }}.zip
          path: ${{ env.ZIP_PATH }}

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_PATH }}
          name: Alt-Click Status ${{ steps.meta.outputs.tag }}
          tag_name: ${{ steps.meta.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- CurseForge: BigWigs Packager ----------------
      - name: Confirm .pkgmeta present at tag
        shell: bash
        run: |
          if [[ ! -f ".pkgmeta" ]]; then
            echo "::error::.pkgmeta missing at tag '${{ steps.meta.outputs.tag }}'."
            echo "You must commit .pkgmeta and create a NEW tag (e.g., v0.3.0f)."
            exit 1
          fi

      - name: Upload to CurseForge (BigWigs Packager)
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          # relies on .pkgmeta + @project-version@ in TOC committed at the tag
          args: -p 1333613
